### ISSUE TITLE
Driving Straight

### ISSUE THREAD

**Issue by erxclau** [fusion479/skystone#25]
Use a PID loop to drive straight
Make use of the current heading and look at angle deviance. If the angle deviates too much from the current heading, turn left or right, depending on whether angle is positive or negative.

Address #23 first

**Comment by erxclau** [comment]
@farhattameem [resource](https://stemrobotics.cs.pdx.edu/node/7268) work on auton branch for now

**Comment by farhattameem** [comment]
It's done
