### ISSUE TITLE
Counts per revolution

### ISSUE THREAD

**Issue by erxclau** [fusion479/skystone#27]
Change counts per revolution from 1120 to 537.6 in drivetrain class.
1120 was for [Neverest 40 motors](https://www.andymark.com/products/neverest-classic-40-gearmotor).

**Comment by erxclau** [comment]
@MattChann this is probably why our robot is so fast without slow mode

**Comment by MattChann** [comment]
@ericlau00 Let's see if we can go faster

**Comment by farhattameem** [comment]
I did it.
