### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by erxclau** [fusion479/skystone#4]
Make your presence known to us by leaving a comment here!

**Comment by Lucas-Lee11** [comment]
let my presence be known; be aware of my presence.

**Comment by MichaelRobertson479** [comment]
gib eth plez
0xe6D0e806646CbfcAF2bdCB2C8662a5Be72942eac

**Comment by vincentw921** [comment]
MY PRESENCE IS TOO STRONG FOR YOU. I AM YOUR LORD AND SAVIOR...

**Comment by Alif-Abdullah0** [comment]
I exist. Hello fellow earthlings. How do you do on this fine day.

**Comment by zawaddewan** [comment]
Hi yes I am a person, how do you do fellow people

**Comment by polinam550** [comment]
I exist?

**Comment by JamesStuy** [comment]
Hi

**Comment by eduardoloz** [comment]
Please acknowledge I am a person too

**Comment by JeffreyJiang19** [comment]
I am here two

**Comment by farhattameem** [comment]
lmao xdddd haha funny meme

**Comment by vicrobex** [comment]
🗿

**Comment by WingJiang** [comment]
Hi

**Comment by ghost** [comment]
my presence is now known acknowledge my presence

**Comment by jamuy321** [comment]
Hi my name's Jeff(rey Mui)

**Comment by HasinRaihan223** [comment]
I assert my dominance by letting my presence being known

**Comment by turtlelazy** [comment]
Hello

**Comment by SeniorMars** [comment]
Hey, 
the name is karl! Check out my dotfiles if you have time.

**Comment by farhattameem** [comment]
∩
　　　　　　　＼＼
　　　　　　　／　 ）
⊂＼＿／￣￣￣　 ／
　＼＿／   ° ͜ʖ ° （
　　　）　　 　／⌒＼
　　／　 ＿＿＿／⌒＼⊃
　（　 ／
　　＼＼
           U

**Comment by glin20** [comment]
Boo

**Comment by ivy102** [comment]
hi

**Comment by ghost** [comment]
Hi.

**Comment by github-hwang** [comment]
Presence...

**Comment by Barndude** [comment]
Me and the bois

**Comment by AbdalAbir** [comment]
Ok im in finally on my phone

**Comment by azheng31** [comment]
hello

**Comment by Slyninja2** [comment]
Hi

**Comment by notPear** [comment]
u suck

**Comment by Startips68** [comment]
Hi

**Comment by erxclau** [comment]
I think I've added everyone to the organization. This invitation does not mean you are going to be on Fusion 479; we will eventually split evenly into teams.
Please reopen this issue with a comment if I forgot to add you.
More anon.

**Comment by vincentw921** [comment]
What do you mean by 2 teams?

**Comment by erxclau** [comment]
@VinoLoser We have two FTC teams: Fusion 479 and Fission 310.

**Comment by vincentw921** [comment]
Is there a difference between the two teams?

**Comment by erxclau** [comment]
@VinoLoser we both compete in the same competitions but we make different bots. there’s no real difference on paper
